// Code generated by vertices Vert.x API generator. DO NOT EDIT.
package vertices
package net

import io.vertx.core.net.NetSocket
import io.vertx.core.net.SocketAddress
import io.vertx.core.net.{ NetClient => JavaNetClient }
import java.lang.String
import monix.eval.Task

case class NetClient(val unwrap: JavaNetClient) extends AnyVal {

  def close(): Unit =
    unwrap.close()

  def connect(arg0: Int, arg1: String): Task[NetSocket] =
    Task.handle[NetSocket] { handler =>
      unwrap.connect(arg0, arg1, handler)
    }

  def connect(arg0: Int, arg1: String, arg2: String): Task[NetSocket] =
    Task.handle[NetSocket] { handler =>
      unwrap.connect(arg0, arg1, arg2, handler)
    }

  def connect(arg0: SocketAddress): Task[NetSocket] =
    Task.handle[NetSocket] { handler =>
      unwrap.connect(arg0, handler)
    }

  def connect(arg0: SocketAddress, arg1: String): Task[NetSocket] =
    Task.handle[NetSocket] { handler =>
      unwrap.connect(arg0, arg1, handler)
    }

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()
}

object NetClient {}
