/*
 * Copyright 2018 David Gregory and the Vertices project contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// $COVERAGE-OFF$
package vertices
package net

import io.vertx.core.Handler
import io.vertx.core.net.SocketAddress
import io.vertx.core.net.{ NetServer => JavaNetServer }
import io.vertx.core.net.{ NetSocket => JavaNetSocket }
import io.vertx.core.streams.ReadStream
import java.lang.String
import java.lang.Throwable
import java.lang.Void
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class NetServer(val unwrap: JavaNetServer) extends AnyVal {

  def actualPort(): Int =
    unwrap.actualPort()

  def close(): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.close(handler)
      }
      .map(_ => ())

  def connectHandler(): Handler[JavaNetSocket] =
    unwrap.connectHandler()

  def connectHandler(arg0: Handler[JavaNetSocket]): NetServer =
    NetServer(unwrap.connectHandler(arg0))

  def connectStream(): ReadStream[JavaNetSocket] =
    unwrap.connectStream()

  def exceptionHandler(arg0: Handler[Throwable]): NetServer =
    NetServer(unwrap.exceptionHandler(arg0))

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()

  def listen(): Task[NetServer] =
    Task
      .handle[JavaNetServer] { handler =>
        unwrap.listen(handler)
      }
      .map(NetServer(_))

  def listen(arg0: Int): Task[NetServer] =
    Task
      .handle[JavaNetServer] { handler =>
        unwrap.listen(arg0, handler)
      }
      .map(NetServer(_))

  def listen(arg0: Int, arg1: String): Task[NetServer] =
    Task
      .handle[JavaNetServer] { handler =>
        unwrap.listen(arg0, arg1, handler)
      }
      .map(NetServer(_))

  def listen(arg0: SocketAddress): Task[NetServer] =
    Task
      .handle[JavaNetServer] { handler =>
        unwrap.listen(arg0, handler)
      }
      .map(NetServer(_))
}

object NetServer {}
// $COVERAGE-ON$
