/*
 * Copyright 2018 David Gregory and the Vertices project contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// $COVERAGE-OFF$
package vertices
package net

import io.vertx.core.Handler
import io.vertx.core.buffer.Buffer
import io.vertx.core.net.SocketAddress
import io.vertx.core.net.{ NetSocket => JavaNetSocket }
import java.lang.String
import java.lang.Throwable
import java.lang.Void
import javax.net.ssl.SSLSession
import javax.security.cert.X509Certificate
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class NetSocket(val unwrap: JavaNetSocket) extends AnyVal {

  def close(): Unit =
    unwrap.close()

  def closeHandler(arg0: Handler[Void]): NetSocket =
    NetSocket(unwrap.closeHandler(arg0))

  def drainHandler(arg0: Handler[Void]): NetSocket =
    NetSocket(unwrap.drainHandler(arg0))

  def end(arg0: Buffer): Unit =
    unwrap.end(arg0)

  def endHandler(arg0: Handler[Void]): NetSocket =
    NetSocket(unwrap.endHandler(arg0))

  def exceptionHandler(arg0: Handler[Throwable]): NetSocket =
    NetSocket(unwrap.exceptionHandler(arg0))

  def handler(arg0: Handler[Buffer]): NetSocket =
    NetSocket(unwrap.handler(arg0))

  def indicatedServerName(): String =
    unwrap.indicatedServerName()

  def isSsl(): Boolean =
    unwrap.isSsl()

  def localAddress(): SocketAddress =
    unwrap.localAddress()

  def pause(): NetSocket =
    NetSocket(unwrap.pause())

  def peerCertificateChain(): Array[X509Certificate] =
    unwrap.peerCertificateChain()

  def remoteAddress(): SocketAddress =
    unwrap.remoteAddress()

  def resume(): NetSocket =
    NetSocket(unwrap.resume())

  def sendFile(arg0: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.sendFile(arg0, handler)
      }
      .map(_ => ())

  def sendFile(arg0: String, arg1: Long): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.sendFile(arg0, arg1, handler)
      }
      .map(_ => ())

  def sendFile(arg0: String, arg1: Long, arg2: Long): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.sendFile(arg0, arg1, arg2, handler)
      }
      .map(_ => ())

  def setWriteQueueMaxSize(arg0: Int): NetSocket =
    NetSocket(unwrap.setWriteQueueMaxSize(arg0))

  def sslSession(): SSLSession =
    unwrap.sslSession()

  def upgradeToSsl(arg0: Handler[Void]): NetSocket =
    NetSocket(unwrap.upgradeToSsl(arg0))

  def upgradeToSsl(arg0: String, arg1: Handler[Void]): NetSocket =
    NetSocket(unwrap.upgradeToSsl(arg0, arg1))

  def write(arg0: Buffer): NetSocket =
    NetSocket(unwrap.write(arg0))

  def write(arg0: String): NetSocket =
    NetSocket(unwrap.write(arg0))

  def write(arg0: String, arg1: String): NetSocket =
    NetSocket(unwrap.write(arg0, arg1))

  def writeHandlerID(): String =
    unwrap.writeHandlerID()

  def writeQueueFull(): Boolean =
    unwrap.writeQueueFull()
}

object NetSocket {}
// $COVERAGE-ON$
