package vertices
package file

import io.vertx.core.buffer.Buffer
import io.vertx.core.file.CopyOptions
import io.vertx.core.file.FileProps
import io.vertx.core.file.FileSystemProps
import io.vertx.core.file.OpenOptions
import io.vertx.core.file.{ AsyncFile => JavaAsyncFile }
import io.vertx.core.file.{ FileSystem => JavaFileSystem }
import java.lang.Boolean
import java.lang.String
import java.lang.Void
import java.util.List
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class FileSystem(val unwrap: JavaFileSystem) extends AnyVal {

  def chmod(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.chmod(arg0, arg1, handler)
      }
      .map(_ => ())

  def chmodBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.chmodBlocking(arg0, arg1))

  def chmodRecursive(arg0: String, arg1: String, arg2: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.chmodRecursive(arg0, arg1, arg2, handler)
      }
      .map(_ => ())

  def chmodRecursiveBlocking(arg0: String, arg1: String, arg2: String): FileSystem =
    FileSystem(unwrap.chmodRecursiveBlocking(arg0, arg1, arg2))

  def chown(arg0: String, arg1: String, arg2: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.chown(arg0, arg1, arg2, handler)
      }
      .map(_ => ())

  def chownBlocking(arg0: String, arg1: String, arg2: String): FileSystem =
    FileSystem(unwrap.chownBlocking(arg0, arg1, arg2))

  def copy(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.copy(arg0, arg1, handler)
      }
      .map(_ => ())

  def copy(arg0: String, arg1: String, arg2: CopyOptions): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.copy(arg0, arg1, arg2, handler)
      }
      .map(_ => ())

  def copyBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.copyBlocking(arg0, arg1))

  def copyRecursive(arg0: String, arg1: String, arg2: Boolean): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.copyRecursive(arg0, arg1, arg2, handler)
      }
      .map(_ => ())

  def copyRecursiveBlocking(arg0: String, arg1: String, arg2: Boolean): FileSystem =
    FileSystem(unwrap.copyRecursiveBlocking(arg0, arg1, arg2))

  def createFile(arg0: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.createFile(arg0, handler)
      }
      .map(_ => ())

  def createFile(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.createFile(arg0, arg1, handler)
      }
      .map(_ => ())

  def createFileBlocking(arg0: String): FileSystem =
    FileSystem(unwrap.createFileBlocking(arg0))

  def createFileBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.createFileBlocking(arg0, arg1))

  def delete(arg0: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.delete(arg0, handler)
      }
      .map(_ => ())

  def deleteBlocking(arg0: String): FileSystem =
    FileSystem(unwrap.deleteBlocking(arg0))

  def deleteRecursive(arg0: String, arg1: Boolean): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.deleteRecursive(arg0, arg1, handler)
      }
      .map(_ => ())

  def deleteRecursiveBlocking(arg0: String, arg1: Boolean): FileSystem =
    FileSystem(unwrap.deleteRecursiveBlocking(arg0, arg1))

  def exists(arg0: String): Task[Boolean] =
    Task
      .handle[java.lang.Boolean] { handler =>
        unwrap.exists(arg0, handler)
      }
      .map(scala.Boolean.unbox(_))

  def existsBlocking(arg0: String): Boolean =
    unwrap.existsBlocking(arg0)

  def fsProps(arg0: String): Task[FileSystemProps] =
    Task.handle[FileSystemProps] { handler =>
      unwrap.fsProps(arg0, handler)
    }

  def fsPropsBlocking(arg0: String): FileSystemProps =
    unwrap.fsPropsBlocking(arg0)

  def link(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.link(arg0, arg1, handler)
      }
      .map(_ => ())

  def linkBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.linkBlocking(arg0, arg1))

  def lprops(arg0: String): Task[FileProps] =
    Task.handle[FileProps] { handler =>
      unwrap.lprops(arg0, handler)
    }

  def lpropsBlocking(arg0: String): FileProps =
    unwrap.lpropsBlocking(arg0)

  def mkdir(arg0: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.mkdir(arg0, handler)
      }
      .map(_ => ())

  def mkdir(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.mkdir(arg0, arg1, handler)
      }
      .map(_ => ())

  def mkdirBlocking(arg0: String): FileSystem =
    FileSystem(unwrap.mkdirBlocking(arg0))

  def mkdirBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.mkdirBlocking(arg0, arg1))

  def mkdirs(arg0: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.mkdirs(arg0, handler)
      }
      .map(_ => ())

  def mkdirs(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.mkdirs(arg0, arg1, handler)
      }
      .map(_ => ())

  def mkdirsBlocking(arg0: String): FileSystem =
    FileSystem(unwrap.mkdirsBlocking(arg0))

  def mkdirsBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.mkdirsBlocking(arg0, arg1))

  def move(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.move(arg0, arg1, handler)
      }
      .map(_ => ())

  def move(arg0: String, arg1: String, arg2: CopyOptions): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.move(arg0, arg1, arg2, handler)
      }
      .map(_ => ())

  def moveBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.moveBlocking(arg0, arg1))

  def open(arg0: String, arg1: OpenOptions): Task[AsyncFile] =
    Task
      .handle[JavaAsyncFile] { handler =>
        unwrap.open(arg0, arg1, handler)
      }
      .map(AsyncFile(_))

  def openBlocking(arg0: String, arg1: OpenOptions): AsyncFile =
    AsyncFile(unwrap.openBlocking(arg0, arg1))

  def props(arg0: String): Task[FileProps] =
    Task.handle[FileProps] { handler =>
      unwrap.props(arg0, handler)
    }

  def propsBlocking(arg0: String): FileProps =
    unwrap.propsBlocking(arg0)

  def readDir(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.readDir(arg0, handler)
    }

  def readDir(arg0: String, arg1: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.readDir(arg0, arg1, handler)
    }

  def readDirBlocking(arg0: String): List[String] =
    unwrap.readDirBlocking(arg0)

  def readDirBlocking(arg0: String, arg1: String): List[String] =
    unwrap.readDirBlocking(arg0, arg1)

  def readFile(arg0: String): Task[Buffer] =
    Task.handle[Buffer] { handler =>
      unwrap.readFile(arg0, handler)
    }

  def readFileBlocking(arg0: String): Buffer =
    unwrap.readFileBlocking(arg0)

  def readSymlink(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.readSymlink(arg0, handler)
    }

  def readSymlinkBlocking(arg0: String): String =
    unwrap.readSymlinkBlocking(arg0)

  def symlink(arg0: String, arg1: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.symlink(arg0, arg1, handler)
      }
      .map(_ => ())

  def symlinkBlocking(arg0: String, arg1: String): FileSystem =
    FileSystem(unwrap.symlinkBlocking(arg0, arg1))

  def truncate(arg0: String, arg1: Long): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.truncate(arg0, arg1, handler)
      }
      .map(_ => ())

  def truncateBlocking(arg0: String, arg1: Long): FileSystem =
    FileSystem(unwrap.truncateBlocking(arg0, arg1))

  def unlink(arg0: String): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.unlink(arg0, handler)
      }
      .map(_ => ())

  def unlinkBlocking(arg0: String): FileSystem =
    FileSystem(unwrap.unlinkBlocking(arg0))

  def writeFile(arg0: String, arg1: Buffer): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.writeFile(arg0, arg1, handler)
      }
      .map(_ => ())

  def writeFileBlocking(arg0: String, arg1: Buffer): FileSystem =
    FileSystem(unwrap.writeFileBlocking(arg0, arg1))
}

object FileSystem {}
