package vertices

import io.vertx.core.Closeable
import io.vertx.core.Future
import io.vertx.core.Handler
import io.vertx.core.json.JsonObject
import io.vertx.core.{ Context => JavaContext }
import java.lang.String
import java.lang.Throwable
import java.lang.Void
import java.util.List
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class Context(val unwrap: JavaContext) extends AnyVal {

  def addCloseHook(arg0: Closeable): Unit =
    unwrap.addCloseHook(arg0)

  def config(): JsonObject =
    unwrap.config()

  def deploymentID(): String =
    unwrap.deploymentID()

  def exceptionHandler(): Handler[Throwable] =
    unwrap.exceptionHandler()

  def exceptionHandler(arg0: Handler[Throwable]): Context =
    Context(unwrap.exceptionHandler(arg0))

  def executeBlocking[T](arg0: Handler[Future[T]]): Task[T] =
    Task.handle[T] { handler =>
      unwrap.executeBlocking(arg0, handler)
    }

  def executeBlocking[T](arg0: Handler[Future[T]], arg1: Boolean): Task[T] =
    Task.handle[T] { handler =>
      unwrap.executeBlocking(arg0, arg1, handler)
    }

  def get[T](arg0: String): T =
    unwrap.get(arg0)

  def getInstanceCount(): Int =
    unwrap.getInstanceCount()

  def isEventLoopContext(): Boolean =
    unwrap.isEventLoopContext()

  def isMultiThreadedWorkerContext(): Boolean =
    unwrap.isMultiThreadedWorkerContext()

  def isWorkerContext(): Boolean =
    unwrap.isWorkerContext()

  def owner(): Vertx =
    Vertx(unwrap.owner())

  def processArgs(): List[String] =
    unwrap.processArgs()

  def put(arg0: String, arg1: AnyRef): Unit =
    unwrap.put(arg0, arg1)

  def remove(arg0: String): Boolean =
    unwrap.remove(arg0)

  def removeCloseHook(arg0: Closeable): Unit =
    unwrap.removeCloseHook(arg0)

  def runOnContext(arg0: Handler[Void]): Unit =
    unwrap.runOnContext(arg0)
}

object Context {

  def isOnEventLoopThread(): Boolean =
    JavaContext.isOnEventLoopThread()

  def isOnVertxThread(): Boolean =
    JavaContext.isOnVertxThread()

  def isOnWorkerThread(): Boolean =
    JavaContext.isOnWorkerThread()
}
