package vertices

import io.vertx.core.Future
import io.vertx.core.Handler
import io.vertx.core.{ WorkerExecutor => JavaWorkerExecutor }
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class WorkerExecutor(val unwrap: JavaWorkerExecutor) extends AnyVal {

  def close(): Unit =
    unwrap.close()

  def executeBlocking[T](arg0: Handler[Future[T]]): Task[T] =
    Task.handle[T] { handler =>
      unwrap.executeBlocking(arg0, handler)
    }

  def executeBlocking[T](arg0: Handler[Future[T]], arg1: Boolean): Task[T] =
    Task.handle[T] { handler =>
      unwrap.executeBlocking(arg0, arg1, handler)
    }

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()
}

object WorkerExecutor {}
