/*
 * Copyright 2018 David Gregory and the Vertices project contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// $COVERAGE-OFF$
package vertices

import io.vertx.core.Future
import io.vertx.core.Handler
import io.vertx.core.{ WorkerExecutor => JavaWorkerExecutor }
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class WorkerExecutor(val unwrap: JavaWorkerExecutor) extends AnyVal {

  def close(): Unit =
    unwrap.close()

  def executeBlocking[T](arg0: Handler[Future[T]]): Task[T] =
    Task.handle[T] { handler =>
      unwrap.executeBlocking(arg0, handler)
    }

  def executeBlocking[T](arg0: Handler[Future[T]], arg1: Boolean): Task[T] =
    Task.handle[T] { handler =>
      unwrap.executeBlocking(arg0, arg1, handler)
    }

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()
}

object WorkerExecutor {}
// $COVERAGE-ON$
