package vertices

import io.vertx.config.ConfigChange
import io.vertx.config.ConfigRetrieverOptions
import io.vertx.config.{ ConfigRetriever => JavaConfigRetriever }
import io.vertx.core.Future
import io.vertx.core.Handler
import io.vertx.core.json.JsonObject
import io.vertx.core.streams.ReadStream
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class ConfigRetriever(val unwrap: JavaConfigRetriever) extends AnyVal {

  def close(): Unit =
    unwrap.close()

  def configStream(): ReadStream[JsonObject] =
    unwrap.configStream()

  def getCachedConfig(): JsonObject =
    unwrap.getCachedConfig()

  def getConfig(): Task[JsonObject] =
    Task.handle[JsonObject] { handler =>
      unwrap.getConfig(handler)
    }

  def listen(arg0: Handler[ConfigChange]): Unit =
    unwrap.listen(arg0)
}

object ConfigRetriever {

  def create(arg0: Vertx): ConfigRetriever =
    ConfigRetriever(JavaConfigRetriever.create(arg0.unwrap))

  def create(arg0: Vertx, arg1: ConfigRetrieverOptions): ConfigRetriever =
    ConfigRetriever(JavaConfigRetriever.create(arg0.unwrap, arg1))

  def getConfigAsFuture(arg0: ConfigRetriever): Future[JsonObject] =
    JavaConfigRetriever.getConfigAsFuture(arg0.unwrap)
}
