package vertices
package datagram

import io.vertx.core.Handler
import io.vertx.core.buffer.Buffer
import io.vertx.core.datagram.DatagramPacket
import io.vertx.core.datagram.{ DatagramSocket => JavaDatagramSocket }
import io.vertx.core.net.SocketAddress
import io.vertx.core.streams.WriteStream
import java.lang.String
import java.lang.Throwable
import java.lang.Void
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class DatagramSocket(val unwrap: JavaDatagramSocket) extends AnyVal {

  def blockMulticastGroup(arg0: String, arg1: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.blockMulticastGroup(arg0, arg1, handler)
      }
      .map(DatagramSocket(_))

  def blockMulticastGroup(arg0: String, arg1: String, arg2: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.blockMulticastGroup(arg0, arg1, arg2, handler)
      }
      .map(DatagramSocket(_))

  def close(): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.close(handler)
      }
      .map(_ => ())

  def endHandler(arg0: Handler[Void]): DatagramSocket =
    DatagramSocket(unwrap.endHandler(arg0))

  def exceptionHandler(arg0: Handler[Throwable]): DatagramSocket =
    DatagramSocket(unwrap.exceptionHandler(arg0))

  def handler(arg0: Handler[DatagramPacket]): DatagramSocket =
    DatagramSocket(unwrap.handler(arg0))

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()

  def listen(arg0: Int, arg1: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.listen(arg0, arg1, handler)
      }
      .map(DatagramSocket(_))

  def listenMulticastGroup(arg0: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.listenMulticastGroup(arg0, handler)
      }
      .map(DatagramSocket(_))

  def listenMulticastGroup(arg0: String, arg1: String, arg2: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.listenMulticastGroup(arg0, arg1, arg2, handler)
      }
      .map(DatagramSocket(_))

  def localAddress(): SocketAddress =
    unwrap.localAddress()

  def pause(): DatagramSocket =
    DatagramSocket(unwrap.pause())

  def resume(): DatagramSocket =
    DatagramSocket(unwrap.resume())

  def send(arg0: Buffer, arg1: Int, arg2: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.send(arg0, arg1, arg2, handler)
      }
      .map(DatagramSocket(_))

  def send(arg0: String, arg1: Int, arg2: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.send(arg0, arg1, arg2, handler)
      }
      .map(DatagramSocket(_))

  def send(arg0: String, arg1: String, arg2: Int, arg3: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.send(arg0, arg1, arg2, arg3, handler)
      }
      .map(DatagramSocket(_))

  def sender(arg0: Int, arg1: String): WriteStream[Buffer] =
    unwrap.sender(arg0, arg1)

  def unlistenMulticastGroup(arg0: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.unlistenMulticastGroup(arg0, handler)
      }
      .map(DatagramSocket(_))

  def unlistenMulticastGroup(arg0: String, arg1: String, arg2: String): Task[DatagramSocket] =
    Task
      .handle[JavaDatagramSocket] { handler =>
        unwrap.unlistenMulticastGroup(arg0, arg1, arg2, handler)
      }
      .map(DatagramSocket(_))
}

object DatagramSocket {}
