package vertices
package shareddata

import io.vertx.core.shareddata.AsyncMap
import io.vertx.core.shareddata.Counter
import io.vertx.core.shareddata.LocalMap
import io.vertx.core.shareddata.Lock
import io.vertx.core.shareddata.{ SharedData => JavaSharedData }
import java.lang.String
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class SharedData(val unwrap: JavaSharedData) extends AnyVal {

  def getAsyncMap[K, V](arg0: String): Task[AsyncMap[K, V]] =
    Task.handle[AsyncMap[K, V]] { handler =>
      unwrap.getAsyncMap(arg0, handler)
    }

  def getClusterWideMap[K, V](arg0: String): Task[AsyncMap[K, V]] =
    Task.handle[AsyncMap[K, V]] { handler =>
      unwrap.getClusterWideMap(arg0, handler)
    }

  def getCounter(arg0: String): Task[Counter] =
    Task.handle[Counter] { handler =>
      unwrap.getCounter(arg0, handler)
    }

  def getLocalMap[K, V](arg0: String): LocalMap[K, V] =
    unwrap.getLocalMap(arg0)

  def getLock(arg0: String): Task[Lock] =
    Task.handle[Lock] { handler =>
      unwrap.getLock(arg0, handler)
    }

  def getLockWithTimeout(arg0: String, arg1: Long): Task[Lock] =
    Task.handle[Lock] { handler =>
      unwrap.getLockWithTimeout(arg0, arg1, handler)
    }
}

object SharedData {}
