/*
 * Copyright 2018 David Gregory and the Vertices project contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// $COVERAGE-OFF$
package vertices
package dns

import io.vertx.core.dns.MxRecord
import io.vertx.core.dns.SrvRecord
import io.vertx.core.dns.{ DnsClient => JavaDnsClient }
import java.lang.String
import java.util.List
import monix.eval.Task

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class DnsClient(val unwrap: JavaDnsClient) extends AnyVal {

  def lookup(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.lookup(arg0, handler)
    }

  def lookup4(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.lookup4(arg0, handler)
    }

  def lookup6(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.lookup6(arg0, handler)
    }

  def resolveA(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveA(arg0, handler)
    }

  def resolveAAAA(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveAAAA(arg0, handler)
    }

  def resolveCNAME(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveCNAME(arg0, handler)
    }

  def resolveMX(arg0: String): Task[List[MxRecord]] =
    Task.handle[List[MxRecord]] { handler =>
      unwrap.resolveMX(arg0, handler)
    }

  def resolveNS(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveNS(arg0, handler)
    }

  def resolvePTR(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.resolvePTR(arg0, handler)
    }

  def resolveSRV(arg0: String): Task[List[SrvRecord]] =
    Task.handle[List[SrvRecord]] { handler =>
      unwrap.resolveSRV(arg0, handler)
    }

  def resolveTXT(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveTXT(arg0, handler)
    }

  def reverseLookup(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.reverseLookup(arg0, handler)
    }
}

object DnsClient {}
// $COVERAGE-ON$
