// Code generated by vertices Vert.x API generator. DO NOT EDIT.
package vertices
package dns

import io.vertx.core.dns.MxRecord
import io.vertx.core.dns.SrvRecord
import io.vertx.core.dns.{ DnsClient => JavaDnsClient }
import java.lang.String
import java.util.List
import monix.eval.Task

case class DnsClient(val unwrap: JavaDnsClient) extends AnyVal {

  def lookup(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.lookup(arg0, handler)
    }

  def lookup4(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.lookup4(arg0, handler)
    }

  def lookup6(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.lookup6(arg0, handler)
    }

  def resolveA(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveA(arg0, handler)
    }

  def resolveAAAA(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveAAAA(arg0, handler)
    }

  def resolveCNAME(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveCNAME(arg0, handler)
    }

  def resolveMX(arg0: String): Task[List[MxRecord]] =
    Task.handle[List[MxRecord]] { handler =>
      unwrap.resolveMX(arg0, handler)
    }

  def resolveNS(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveNS(arg0, handler)
    }

  def resolvePTR(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.resolvePTR(arg0, handler)
    }

  def resolveSRV(arg0: String): Task[List[SrvRecord]] =
    Task.handle[List[SrvRecord]] { handler =>
      unwrap.resolveSRV(arg0, handler)
    }

  def resolveTXT(arg0: String): Task[List[String]] =
    Task.handle[List[String]] { handler =>
      unwrap.resolveTXT(arg0, handler)
    }

  def reverseLookup(arg0: String): Task[String] =
    Task.handle[String] { handler =>
      unwrap.reverseLookup(arg0, handler)
    }
}

object DnsClient {}
