// Code generated by vertices Vert.x API generator. DO NOT EDIT.
package vertices
package http

import io.vertx.core.Handler
import io.vertx.core.http.HttpConnection
import io.vertx.core.http.HttpServerRequest
import io.vertx.core.http.ServerWebSocket
import io.vertx.core.http.{ HttpServer => JavaHttpServer }
import io.vertx.core.streams.ReadStream
import java.lang.String
import java.lang.Throwable
import java.lang.Void
import monix.eval.Task

case class HttpServer(val unwrap: JavaHttpServer) extends AnyVal {

  def actualPort(): Int =
    unwrap.actualPort()

  def close(): Task[Unit] =
    Task
      .handle[Void] { handler =>
        unwrap.close(handler)
      }
      .map(_ => ())

  def connectionHandler(arg0: Handler[HttpConnection]): HttpServer =
    HttpServer(unwrap.connectionHandler(arg0))

  def exceptionHandler(arg0: Handler[Throwable]): HttpServer =
    HttpServer(unwrap.exceptionHandler(arg0))

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()

  def listen(): Task[HttpServer] =
    Task
      .handle[JavaHttpServer] { handler =>
        unwrap.listen(handler)
      }
      .map(HttpServer(_))

  def listen(arg0: Int): Task[HttpServer] =
    Task
      .handle[JavaHttpServer] { handler =>
        unwrap.listen(arg0, handler)
      }
      .map(HttpServer(_))

  def listen(arg0: Int, arg1: String): Task[HttpServer] =
    Task
      .handle[JavaHttpServer] { handler =>
        unwrap.listen(arg0, arg1, handler)
      }
      .map(HttpServer(_))

  def requestHandler(): Handler[HttpServerRequest] =
    unwrap.requestHandler()

  def requestHandler(arg0: Handler[HttpServerRequest]): HttpServer =
    HttpServer(unwrap.requestHandler(arg0))

  def requestStream(): ReadStream[HttpServerRequest] =
    unwrap.requestStream()

  def websocketHandler(): Handler[ServerWebSocket] =
    unwrap.websocketHandler()

  def websocketHandler(arg0: Handler[ServerWebSocket]): HttpServer =
    HttpServer(unwrap.websocketHandler(arg0))

  def websocketStream(): ReadStream[ServerWebSocket] =
    unwrap.websocketStream()
}

object HttpServer {}
