package vertices
package http

import io.vertx.core.Future
import io.vertx.core.Handler
import io.vertx.core.MultiMap
import io.vertx.core.http.HttpClientRequest
import io.vertx.core.http.HttpClientResponse
import io.vertx.core.http.HttpMethod
import io.vertx.core.http.RequestOptions
import io.vertx.core.http.WebSocket
import io.vertx.core.http.WebsocketVersion
import io.vertx.core.http.{ HttpClient => JavaHttpClient }
import io.vertx.core.streams.ReadStream
import java.lang.String
import java.lang.Throwable
import java.util.function.Function

/**
 * Code generated by vertices Vert.x API generator. DO NOT EDIT.
 */
case class HttpClient(val unwrap: JavaHttpClient) extends AnyVal {

  def close(): Unit =
    unwrap.close()

  def delete(arg0: Int, arg1: String, arg2: String): HttpClientRequest =
    unwrap.delete(arg0, arg1, arg2)

  def delete(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.delete(arg0, arg1, arg2, arg3)

  def delete(arg0: RequestOptions): HttpClientRequest =
    unwrap.delete(arg0)

  def delete(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.delete(arg0, arg1)

  def delete(arg0: String): HttpClientRequest =
    unwrap.delete(arg0)

  def delete(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.delete(arg0, arg1)

  def delete(arg0: String, arg1: String): HttpClientRequest =
    unwrap.delete(arg0, arg1)

  def delete(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.delete(arg0, arg1, arg2)

  def deleteAbs(arg0: String): HttpClientRequest =
    unwrap.deleteAbs(arg0)

  def deleteAbs(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.deleteAbs(arg0, arg1)

  def get(arg0: Int, arg1: String, arg2: String): HttpClientRequest =
    unwrap.get(arg0, arg1, arg2)

  def get(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.get(arg0, arg1, arg2, arg3)

  def get(arg0: RequestOptions): HttpClientRequest =
    unwrap.get(arg0)

  def get(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.get(arg0, arg1)

  def get(arg0: String): HttpClientRequest =
    unwrap.get(arg0)

  def get(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.get(arg0, arg1)

  def get(arg0: String, arg1: String): HttpClientRequest =
    unwrap.get(arg0, arg1)

  def get(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.get(arg0, arg1, arg2)

  def getAbs(arg0: String): HttpClientRequest =
    unwrap.getAbs(arg0)

  def getAbs(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.getAbs(arg0, arg1)

  def getNow(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.getNow(arg0, arg1, arg2, arg3))

  def getNow(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.getNow(arg0, arg1))

  def getNow(arg0: String, arg1: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.getNow(arg0, arg1))

  def getNow(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.getNow(arg0, arg1, arg2))

  def head(arg0: Int, arg1: String, arg2: String): HttpClientRequest =
    unwrap.head(arg0, arg1, arg2)

  def head(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.head(arg0, arg1, arg2, arg3)

  def head(arg0: RequestOptions): HttpClientRequest =
    unwrap.head(arg0)

  def head(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.head(arg0, arg1)

  def head(arg0: String): HttpClientRequest =
    unwrap.head(arg0)

  def head(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.head(arg0, arg1)

  def head(arg0: String, arg1: String): HttpClientRequest =
    unwrap.head(arg0, arg1)

  def head(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.head(arg0, arg1, arg2)

  def headAbs(arg0: String): HttpClientRequest =
    unwrap.headAbs(arg0)

  def headAbs(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.headAbs(arg0, arg1)

  def headNow(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.headNow(arg0, arg1, arg2, arg3))

  def headNow(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.headNow(arg0, arg1))

  def headNow(arg0: String, arg1: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.headNow(arg0, arg1))

  def headNow(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.headNow(arg0, arg1, arg2))

  def isMetricsEnabled(): Boolean =
    unwrap.isMetricsEnabled()

  def options(arg0: Int, arg1: String, arg2: String): HttpClientRequest =
    unwrap.options(arg0, arg1, arg2)

  def options(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.options(arg0, arg1, arg2, arg3)

  def options(arg0: RequestOptions): HttpClientRequest =
    unwrap.options(arg0)

  def options(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.options(arg0, arg1)

  def options(arg0: String): HttpClientRequest =
    unwrap.options(arg0)

  def options(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.options(arg0, arg1)

  def options(arg0: String, arg1: String): HttpClientRequest =
    unwrap.options(arg0, arg1)

  def options(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.options(arg0, arg1, arg2)

  def optionsAbs(arg0: String): HttpClientRequest =
    unwrap.optionsAbs(arg0)

  def optionsAbs(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.optionsAbs(arg0, arg1)

  def optionsNow(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.optionsNow(arg0, arg1, arg2, arg3))

  def optionsNow(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.optionsNow(arg0, arg1))

  def optionsNow(arg0: String, arg1: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.optionsNow(arg0, arg1))

  def optionsNow(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClient =
    HttpClient(unwrap.optionsNow(arg0, arg1, arg2))

  def post(arg0: Int, arg1: String, arg2: String): HttpClientRequest =
    unwrap.post(arg0, arg1, arg2)

  def post(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.post(arg0, arg1, arg2, arg3)

  def post(arg0: RequestOptions): HttpClientRequest =
    unwrap.post(arg0)

  def post(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.post(arg0, arg1)

  def post(arg0: String): HttpClientRequest =
    unwrap.post(arg0)

  def post(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.post(arg0, arg1)

  def post(arg0: String, arg1: String): HttpClientRequest =
    unwrap.post(arg0, arg1)

  def post(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.post(arg0, arg1, arg2)

  def postAbs(arg0: String): HttpClientRequest =
    unwrap.postAbs(arg0)

  def postAbs(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.postAbs(arg0, arg1)

  def put(arg0: Int, arg1: String, arg2: String): HttpClientRequest =
    unwrap.put(arg0, arg1, arg2)

  def put(arg0: Int, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.put(arg0, arg1, arg2, arg3)

  def put(arg0: RequestOptions): HttpClientRequest =
    unwrap.put(arg0)

  def put(arg0: RequestOptions, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.put(arg0, arg1)

  def put(arg0: String): HttpClientRequest =
    unwrap.put(arg0)

  def put(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.put(arg0, arg1)

  def put(arg0: String, arg1: String): HttpClientRequest =
    unwrap.put(arg0, arg1)

  def put(arg0: String, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.put(arg0, arg1, arg2)

  def putAbs(arg0: String): HttpClientRequest =
    unwrap.putAbs(arg0)

  def putAbs(arg0: String, arg1: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.putAbs(arg0, arg1)

  def redirectHandler(): Function[HttpClientResponse, Future[HttpClientRequest]] =
    unwrap.redirectHandler()

  def redirectHandler(arg0: Function[HttpClientResponse, Future[HttpClientRequest]]): HttpClient =
    HttpClient(unwrap.redirectHandler(arg0))

  def request(arg0: HttpMethod, arg1: Int, arg2: String, arg3: String): HttpClientRequest =
    unwrap.request(arg0, arg1, arg2, arg3)

  def request(
    arg0: HttpMethod,
    arg1: Int,
    arg2: String,
    arg3: String,
    arg4: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.request(arg0, arg1, arg2, arg3, arg4)

  def request(arg0: HttpMethod, arg1: RequestOptions): HttpClientRequest =
    unwrap.request(arg0, arg1)

  def request(arg0: HttpMethod, arg1: RequestOptions, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.request(arg0, arg1, arg2)

  def request(arg0: HttpMethod, arg1: String): HttpClientRequest =
    unwrap.request(arg0, arg1)

  def request(arg0: HttpMethod, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.request(arg0, arg1, arg2)

  def request(arg0: HttpMethod, arg1: String, arg2: String): HttpClientRequest =
    unwrap.request(arg0, arg1, arg2)

  def request(arg0: HttpMethod, arg1: String, arg2: String, arg3: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.request(arg0, arg1, arg2, arg3)

  def requestAbs(arg0: HttpMethod, arg1: String): HttpClientRequest =
    unwrap.requestAbs(arg0, arg1)

  def requestAbs(arg0: HttpMethod, arg1: String, arg2: Handler[HttpClientResponse]): HttpClientRequest =
    unwrap.requestAbs(arg0, arg1, arg2)

  def websocket(arg0: Int, arg1: String, arg2: String, arg3: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(arg0: Int, arg1: String, arg2: String, arg3: Handler[WebSocket], arg4: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(arg0: Int, arg1: String, arg2: String, arg3: MultiMap, arg4: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: Handler[WebSocket],
    arg5: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocket(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: WebsocketVersion,
    arg5: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocket(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: WebsocketVersion,
    arg5: Handler[WebSocket],
    arg6: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5, arg6))

  def websocket(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: WebsocketVersion,
    arg5: String,
    arg6: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5, arg6))

  def websocket(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: WebsocketVersion,
    arg5: String,
    arg6: Handler[WebSocket],
    arg7: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7))

  def websocket(arg0: RequestOptions, arg1: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1))

  def websocket(arg0: RequestOptions, arg1: Handler[WebSocket], arg2: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2))

  def websocket(arg0: RequestOptions, arg1: MultiMap, arg2: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2))

  def websocket(arg0: RequestOptions, arg1: MultiMap, arg2: Handler[WebSocket], arg3: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(arg0: RequestOptions, arg1: MultiMap, arg2: WebsocketVersion, arg3: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(
    arg0: RequestOptions,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: Handler[WebSocket],
    arg4: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: RequestOptions,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: String,
    arg4: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: RequestOptions,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: String,
    arg4: Handler[WebSocket],
    arg5: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocket(arg0: String, arg1: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1))

  def websocket(arg0: String, arg1: Handler[WebSocket], arg2: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2))

  def websocket(arg0: String, arg1: MultiMap, arg2: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2))

  def websocket(arg0: String, arg1: MultiMap, arg2: Handler[WebSocket], arg3: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(arg0: String, arg1: MultiMap, arg2: WebsocketVersion, arg3: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(
    arg0: String,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: Handler[WebSocket],
    arg4: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: String,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: String,
    arg4: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: String,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: String,
    arg4: Handler[WebSocket],
    arg5: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocket(arg0: String, arg1: String, arg2: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2))

  def websocket(arg0: String, arg1: String, arg2: Handler[WebSocket], arg3: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(arg0: String, arg1: String, arg2: MultiMap, arg3: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3))

  def websocket(
    arg0: String,
    arg1: String,
    arg2: MultiMap,
    arg3: Handler[WebSocket],
    arg4: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: String,
    arg1: String,
    arg2: MultiMap,
    arg3: WebsocketVersion,
    arg4: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4))

  def websocket(
    arg0: String,
    arg1: String,
    arg2: MultiMap,
    arg3: WebsocketVersion,
    arg4: Handler[WebSocket],
    arg5: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocket(
    arg0: String,
    arg1: String,
    arg2: MultiMap,
    arg3: WebsocketVersion,
    arg4: String,
    arg5: Handler[WebSocket]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocket(
    arg0: String,
    arg1: String,
    arg2: MultiMap,
    arg3: WebsocketVersion,
    arg4: String,
    arg5: Handler[WebSocket],
    arg6: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocket(arg0, arg1, arg2, arg3, arg4, arg5, arg6))

  def websocketAbs(
    arg0: String,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: String,
    arg4: Handler[WebSocket],
    arg5: Handler[Throwable]): HttpClient =
    HttpClient(unwrap.websocketAbs(arg0, arg1, arg2, arg3, arg4, arg5))

  def websocketStream(arg0: Int, arg1: String, arg2: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2)

  def websocketStream(arg0: Int, arg1: String, arg2: String, arg3: MultiMap): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3)

  def websocketStream(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: WebsocketVersion): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3, arg4)

  def websocketStream(
    arg0: Int,
    arg1: String,
    arg2: String,
    arg3: MultiMap,
    arg4: WebsocketVersion,
    arg5: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3, arg4, arg5)

  def websocketStream(arg0: RequestOptions): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0)

  def websocketStream(arg0: RequestOptions, arg1: MultiMap): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1)

  def websocketStream(arg0: RequestOptions, arg1: MultiMap, arg2: WebsocketVersion): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2)

  def websocketStream(
    arg0: RequestOptions,
    arg1: MultiMap,
    arg2: WebsocketVersion,
    arg3: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3)

  def websocketStream(arg0: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0)

  def websocketStream(arg0: String, arg1: MultiMap): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1)

  def websocketStream(arg0: String, arg1: MultiMap, arg2: WebsocketVersion): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2)

  def websocketStream(arg0: String, arg1: MultiMap, arg2: WebsocketVersion, arg3: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3)

  def websocketStream(arg0: String, arg1: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1)

  def websocketStream(arg0: String, arg1: String, arg2: MultiMap): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2)

  def websocketStream(arg0: String, arg1: String, arg2: MultiMap, arg3: WebsocketVersion): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3)

  def websocketStream(
    arg0: String,
    arg1: String,
    arg2: MultiMap,
    arg3: WebsocketVersion,
    arg4: String): ReadStream[WebSocket] =
    unwrap.websocketStream(arg0, arg1, arg2, arg3, arg4)

  def websocketStreamAbs(arg0: String, arg1: MultiMap, arg2: WebsocketVersion, arg3: String): ReadStream[WebSocket] =
    unwrap.websocketStreamAbs(arg0, arg1, arg2, arg3)
}

object HttpClient {}
